

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG     #logs the sql statements
                type:
                    descriptor:
                        sql:
                            BasicBinder:
                                TRACE

            apache:
                kafka:
                    clients:
                        producer: DEBUG

server:
    port: 9002

spring:
    datasource:
        password: new_password
        url: jdbc:mysql://localhost:3306/vehicle
        username: root



    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
            group-id: vehicle-events
            auto-offset-reset: earliest
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

    jpa:
        hibernate:
            ddl-auto: update


